return {
	-- ====================
	-- lint_module = require ("modular.modules.LintModule")
	-- lsp_nvim_cmp_completion_module = require ("modular.modules._LspNvimCmpCompletionModule"),
	-- lspsaga_module = require ("modular.modules.LspSagaModule"),
	-- menu_module = require ("modular.modules.MenuModule"),
	-- temporary_module1 = require ("modular.modules.TemporaryModule1"),
	-- _menu_module = require ("modular.modules._MenuModule"),
	-- _github_module = require ("modular.modules._GithubModule"),
	-- _lspnvimcmpcompletion_module = require ("modular.modules._LspNvimCmpCompletionModule"),
	-- temporary_module = require ("modular.modules.TemporaryModule1"),
	ai_module = require ("modular.modules.AiModule"),
	basic_module = require ("modular.modules.BasicModule"),
	clang_module = require ("modular.modules.ClangModule"),
	compiler_module = require ("modular.modules.CompilerModule"),
	dap_module = require ("modular.modules.DapModule"),
	db_module = require ("modular.modules.DbModule"),
	doc_module = require ("modular.modules.DocModule"),
	formatter_module = require ("modular.modules.FormatterModule"),
	gdb_module = require ("modular.modules.GdbModule"),
	git_module = require ("modular.modules.GitModule"),
	iron_module = require ("modular.modules.IronModule"),
	java_module = require ("modular.modules.JavaMoule"),
	lean_module = require ("modular.modules.LeanModule"),
	lint_module = require ("modular.modules.LintModule"),
	lsp_module = require ("modular.modules.LspModule"),
	lspsaga_module = require ("modular.modules.LspSagaModule"),
	md_module = require ("modular.modules.MdModule"),
	misc_module = require ("modular.modules.MiscModule"),
	nvim_module = require ("modular.modules.NvimModule"),
	org_module = require ("modular.modules.OrgModule"),
	profiler_module = require ("modular.modules.ProfilerModule"),
	-- rest_module = require ("modular.modules.RestModule"),
	test_module = require ("modular.modules.TestModule"),
	ui_module = require ("modular.modules.UIModule"),
	github_module = require ("modular.modules.GithubModule"),
}
