local map = vim.keymap.set

map ("n", "<leader>cor", vim.cmd.CMakeOpenRunner, { desc = "runner" })
map ("n", "<leader>coe", vim.cmd.CMakeOpenExecutor, { desc = "executor" })
map ("n", "<leader>coc", vim.cmd.CMakeOpenCache, { desc = "cache" })
map ("n", "<leader>ccr", vim.cmd.CMakeCloseRunner, { desc = "runner" })
map ("n", "<leader>cce", vim.cmd.CMakeCloseExecutor, { desc = "executor" })
map ("n", "<leader>csr", vim.cmd.CMakeStopRunner, { desc = "runner" })
map ("n", "<leader>cse", vim.cmd.CMakeStopExecutor, { desc = "executor" })

map ("n", "<leader>ccR", function ()
	vim.cmd.CMakeStopRunner ()
	vim.cmd.CMakeCloseRunner ()
end, { desc = "runner stop and close" })
map ("n", "<leader>ccE", function ()
	vim.cmd.CMakeStopExecutor ()
	vim.cmd.CMakeCloseExecutor ()
end, { desc = "executor stop and close" })

map ("n", "<leader>csR", function ()
	vim.cmd.CMakeStopRunner ()
	vim.cmd.CMakeCloseRunner ()
end, { desc = "runner stop and close" })
map ("n", "<leader>csE", function ()
	vim.cmd.CMakeStopExecutor ()
	vim.cmd.CMakeCloseExecutor ()
end, { desc = "executor stop and close" })

map ("n", "<leader>cg", vim.cmd.CMakeGenerate, { desc = "cmake generate" })
map ("n", "<leader>cb", vim.cmd.CMakeBuild, { desc = "cmake build" })
map ("n", "<leader>cr", vim.cmd.CMakeRun, { desc = "cmake run" })
map ("n", "<leader>cd", vim.cmd.CMakeDebug, { desc = "cmake debug" })
map ("n", "<leader>cC", vim.cmd.CMakeClean, { desc = "cmake clean" })
