local map = vim.keymap.set

-- map ("n", "<leader>db", vim.cmd.DapToggleBreakpoint)
-- map ("n", "<leader>dc", vim.cmd.DapContinue)
-- map ("n", "<leader>dd", vim.cmd.DapDisconnect)
-- map ("n", "<leader>dp", vim.cmd.DapPause)
-- map ("n", "<leader>dt", vim.cmd.DapTerminate)
-- map ("n", "<leader>dv", vim.cmd.DapVirtualTextToggle)

map ("n", "<leader>db", require ("dap").toggle_breakpoint)
map ("n", "<leader>dB", function()
	require ("dap").set_breakpoint (vim.fn.input "Breakpoint condition: ")
end)
map ("n", "<leader>dc", require ("dap").continue)
map ("n", "<leader>dd", require ("dap").disconnect)
map ("n", "<leader>dp", require ("dap").pause)
map ("n", "<leader>dt", require ("dap").terminate)
map ("n", "<leader>dv", require ("nvim-dap-virtual-text").toggle)
map ("n", "<leader>dso", require ("dap").step_over)
map ("n", "<leader>dsi", require ("dap").step_into)
map ("n", "<leader>dsO", require ("dap").step_out)
map ("n", "<leader>dsI", require ("dap").step_back)
