local map = vim.keymap.set
local builtin = require("telescope.builtin")

map("n", "<leader>F", builtin.resume)
map("n", "<leader>f", builtin.planets)
map("n", "<leader>f/", builtin.search_history)
map("n", "<leader>f:", builtin.command_history)
map("n", "<leader>fA", builtin.treesitter)
map("n", "<leader>fD", builtin.diagnostics)
map("n", "<leader>fQ", builtin.quickfixhistory)
map("n", "<leader>fa", "<cmd>Telescope find_files follow=true no_ignore=true hidden=true<CR>")
map("n", "<leader>fb", builtin.buffers)
map("n", "<leader>ff", builtin.find_files)
map("n", "<leader>fg", builtin.grep_string)
map("n", "<leader>fh", builtin.help_tags)
map("n", "<leader>fj", builtin.jumplist)
map("n", "<leader>fm", builtin.marks)
map("n", "<leader>fo", builtin.oldfiles)
map("n", "<leader>fq", builtin.quickfix)
map("n", "<leader>ft", "<cmd>Telescope telescope-tabs list_tabs<CR>")
map("n", "<leader>fus", function () require("telescope").extensions.undo.undo({ saved_only = true }) end)
map("n", "<leader>fuu", function () require("telescope").extensions.undo.undo() end)
map("n", "<leader>fv", builtin.vim_options)
map("n", "<leader>fw", builtin.live_grep)
map("n", "<leader>fz", builtin.current_buffer_fuzzy_find)

vim.api.nvim_create_autocmd('LspAttach', {
	callback = function(args)
		local map = vim.keymap.set
		local builtin = require("telescope.builtin")

		map("n", "<leader>fI", builtin.lsp_incoming_calls)
		map("n", "<leader>fO", builtin.lsp_outgoing_calls)
		map("n", "<leader>fS", builtin.lsp_dynamic_workspace_symbols)
		map("n", "<leader>fd", builtin.lsp_definitions)
		map("n", "<leader>fi", builtin.lsp_implementations)
		map("n", "<leader>fr", builtin.lsp_references)
		map("n", "<leader>fs", builtin.lsp_document_symbols)
	end,
})
