local map = vim.keymap.set
local FzfLua = require ("fzf-lua")

map ("n", "<leader>F", FzfLua.resume, { desc = "FzfLua resume" })
-- map ("n", "<leader>f", builtin.planets)
map ("n", "<leader>f/", FzfLua.search_history, { desc = "search history" })
map ("n", "<leader>f:", FzfLua.command_history, { desc = "command history" })
map ("n", "<leader>fA", FzfLua.treesitter, { desc = "treesitter" })
-- map ("n", "<leader>fD", FzfLua.diagnostics, { desc = "diagnostics" })
map ("n", "<leader>fDd", FzfLua.diagnostics_document, { desc = "document diagnostics" })
map ("n", "<leader>fDw", FzfLua.diagnostics_workspace, { desc = "workspace diagnostics" })
-- map ("n", "<leader>fG", function () telescope.extensions.ast_grep.ast_grep () end, { desc = "grep ast" })
-- map ("n", "<leader>fQ", FzfLua.quickfixhistory, { desc = "quickfixhistory" })
map ("n", "<leader>fQ", FzfLua.quickfix_stack, { desc = "quickfixhistory" })
map ("n", "<leader>fQ", FzfLua.registers, { desc = "registers" })
-- map ("n", "<leader>fa", function () FzfLua.find_files { follow=true, no_ignore=true, hidden=true} end, { desc = "all files" })
map ("n", "<leader>fb", FzfLua.buffers, { desc = "buffers" })
map ("n", "<leader>fc", FzfLua.colorschemes, { desc = "colorschemes" })
map ("n", "<leader>ff", FzfLua.files, { desc = "find files" })
-- map ("n", "<leader>fg", FzfLua.grep_string, { desc = "grep string" })
map ("n", "<leader>fh", FzfLua.help_tags, { desc = "help tags" })
-- map ("n", "<leader>fj", FzfLua.jumplist, { desc = "jumplist" })
map ("n", "<leader>fj", FzfLua.jumps, { desc = "jumplist" })
map ("n", "<leader>fm", FzfLua.marks, { desc = "marks" })
map ("n", "<leader>fo", function () FzfLua.oldfiles { cwd = vim.fn.getcwd () } end, { desc = "oldfiles" })
map ("n", "<leader>fq", FzfLua.quickfix, { desc = "quickfix" })
-- map ("n", "<leader>ft", function () require ("telescope-tabs").list_tabs () end, { desc = "tabs" })
-- map ("n", "<leader>fus", function () telescope.extensions.undo.undo({ saved_only = true }) end, { desc = "saved" })
-- map ("n", "<leader>fuu", telescope.extensions.undo.undo, { desc = "undo" })
-- map ("n", "<leader>fv", FzfLua.vim_options, { desc = "vim options" })
map ("n", "<leader>fv", FzfLua.nvim_options, { desc = "nvim options" })
map ("n", "<leader>fw", FzfLua.live_grep, { desc = "live grep" })
-- map ("n", "<leader>fz", FzfLua.current_buffer_fuzzy_find, { desc = "current buffer fuzzy find" })
