local map = vim.keymap.set
local builtin = require("telescope.builtin")

map ("n", "<leader>F", builtin.resume, { desc = "resume" })
-- map ("n", "<leader>f", builtin.planets)
map ("n", "<leader>f/", builtin.search_history, { desc = "search history" })
map ("n", "<leader>f:", builtin.command_history, { desc = "command history" })
map ("n", "<leader>fA", builtin.treesitter, { desc = "treesitter" })
map ("n", "<leader>fD", builtin.diagnostics, { desc = "diagnostics" })
map ("n", "<leader>fQ", builtin.quickfixhistory, { desc = "quickfixhistory" })
map ("n", "<leader>fQ", builtin.registers, { desc = "registers" })
map ("n", "<leader>fa", "<cmd>Telescope find_files follow=true no_ignore=true hidden=true<CR>", { desc = "all files" })
map ("n", "<leader>fb", builtin.buffers, { desc = "buffers" })
map ("n", "<leader>ff", builtin.find_files, { desc = "find files" })
map ("n", "<leader>fg", builtin.grep_string, { desc = "grep string" })
map ("n", "<leader>fh", builtin.help_tags, { desc = "help tags" })
map ("n", "<leader>fj", builtin.jumplist, { desc = "jumplist" })
map ("n", "<leader>fm", builtin.marks, { desc = "marks" })
map ("n", "<leader>fo", builtin.oldfiles, { desc = "oldfiles" })
map ("n", "<leader>fq", builtin.quickfix, { desc = "quickfix" })
map ("n", "<leader>ft", "<cmd>Telescope telescope-tabs list_tabs<CR>", { desc = "tabs" })
map ("n", "<leader>fus", function () require("telescope").extensions.undo.undo({ saved_only = true }) end, { desc = "saved" })
map ("n", "<leader>fuu", require("telescope").extensions.undo.undo, { desc = "undo" })
map ("n", "<leader>fv", builtin.vim_options, { desc = "vim options" })
map ("n", "<leader>fw", builtin.live_grep, { desc = "live grep" })
map ("n", "<leader>fz", builtin.current_buffer_fuzzy_find, { desc = "current buffer fuzzy find" })
