local map = vim.keymap.set
local builtin = require("telescope.builtin")

map ("n", "<leader>F", builtin.resume, { desc = "telescope resume" })
-- map ("n", "<leader>f", builtin.planets)
map ("n", "<leader>f/", builtin.search_history, { desc = "telescope search_history" })
map ("n", "<leader>f:", builtin.command_history, { desc = "telescope command_history" })
map ("n", "<leader>fA", builtin.treesitter, { desc = "telescope treesitter" })
map ("n", "<leader>fD", builtin.diagnostics, { desc = "telescope diagnostics" })
map ("n", "<leader>fQ", builtin.quickfixhistory, { desc = "telescope quickfixhistory" })
map ("n", "<leader>fQ", builtin.registers, { desc = "telescope registers" })
map ("n", "<leader>fa", "<cmd>Telescope find_files follow=true no_ignore=true hidden=true<CR>", { desc = "telescope all files" })
map ("n", "<leader>fb", builtin.buffers, { desc = "telescope buffers" })
map ("n", "<leader>ff", builtin.find_files, { desc = "telescope find_files" })
map ("n", "<leader>fg", builtin.grep_string, { desc = "telescope grep_string" })
map ("n", "<leader>fh", builtin.help_tags, { desc = "telescope help_tags" })
map ("n", "<leader>fj", builtin.jumplist, { desc = "telescope jumplist" })
map ("n", "<leader>fm", builtin.marks, { desc = "telescope marks" })
map ("n", "<leader>fo", builtin.oldfiles, { desc = "telescope oldfiles" })
map ("n", "<leader>fq", builtin.quickfix, { desc = "telescope quickfix" })
map ("n", "<leader>ft", "<cmd>Telescope telescope-tabs list_tabs<CR>", { desc = "telescope tabs" })
map ("n", "<leader>fus", function () require("telescope").extensions.undo.undo({ saved_only = true }) end, { desc = "telescope undo saveds" })
map ("n", "<leader>fuu", require("telescope").extensions.undo.undo, { desc = "telescope undo" })
map ("n", "<leader>fv", builtin.vim_options, { desc = "telescope vim_options" })
map ("n", "<leader>fw", builtin.live_grep, { desc = "telescope live_grep" })
map ("n", "<leader>fz", builtin.current_buffer_fuzzy_find, { desc = "telescope current_buffer_fuzzy_find" })
