local map = vim.keymap.set
local telescope = require ("telescope")
local telescope_builtin = require ("telescope.builtin")

map ("n", "<leader>F", telescope_builtin.resume, { desc = "telescope resume" })
-- map ("n", "<leader>f", builtin.planets)
map ("n", "<leader>f/", telescope_builtin.search_history, { desc = "search history" })
map ("n", "<leader>f:", telescope_builtin.command_history, { desc = "command history" })
map ("n", "<leader>fA", telescope_builtin.treesitter, { desc = "treesitter" })
map ("n", "<leader>fDd", function () telescope_builtin.diagnostics ({ bufnr = 0 }) end, { desc = "document diagnostics" })
map ("n", "<leader>fDw", function () telescope_builtin.diagnostics ({ bufnr = nil }) end, { desc = "workspace diagnostics" })
map ("n", "<leader>fQ", telescope_builtin.quickfixhistory, { desc = "quickfixhistory" })
map ("n", "<leader>fR", telescope_builtin.registers, { desc = "registers" })
map ("n", "<leader>fa", function () telescope_builtin.find_files { follow=true, no_ignore=true, hidden=true} end, { desc = "all files" })
map ("n", "<leader>fb", telescope_builtin.buffers, { desc = "buffers" })
map ("n", "<leader>ff", telescope_builtin.find_files, { desc = "find files" })
map ("n", "<leader>fga", function () telescope.extensions.ast_grep.ast_grep () end, { desc = "grep ast" })
map ("n", "<leader>fgg", telescope_builtin.grep_string, { desc = "grep string" })
map ("n", "<leader>fh", telescope_builtin.help_tags, { desc = "help tags" })
map ("n", "<leader>fj", telescope_builtin.jumplist, { desc = "jumplist" })
map ("n", "<leader>fm", telescope_builtin.marks, { desc = "marks" })
map ("n", "<leader>fo", function () telescope_builtin.oldfiles { cwd = vim.fn.getcwd () } end, { desc = "oldfiles" })
map ("n", "<leader>fq", telescope_builtin.quickfix, { desc = "quickfix" })
map ("n", "<leader>ft", function () require ("telescope-tabs").list_tabs () end, { desc = "tabs" })
map ("n", "<leader>fus", function () telescope.extensions.undo.undo({ saved_only = true }) end, { desc = "saved" })
map ("n", "<leader>fuu", telescope.extensions.undo.undo, { desc = "undo" })
map ("n", "<leader>uu", telescope.extensions.undo.undo, { desc = "undo tree" })
map ("n", "<leader>fv", telescope_builtin.vim_options, { desc = "vim options" })
map ("n", "<leader>fw", telescope_builtin.live_grep, { desc = "live grep" })
map ("n", "<leader>fz", telescope_builtin.current_buffer_fuzzy_find, { desc = "current buffer fuzzy find" })
